version: '3.3'

name: api-template-postgreSQL

services:
  # api-dev:
  #   container_name: api-dev
  #   image: api-dev:1.0.0
  #   build:
  #     context: .
  #     target: development
  #     dockerfile: ./Dockerfile
  #   command: yarn start:debug
  #   ports:
  #     - 8000:8000
  #   networks:
  #     - api-network
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   restart: unless-stopped

  postgres:
    image: postgres
    container_name: api-postgresDB
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: api_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    ports:
      - '5050:80'
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: always

volumes:
  postgres-data:
# networks:
#   api-network:
